name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up latest Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - id: build
        name: Build
        run: npx tsx .github/bin/release.mts
      - name: Test
        run: |
          echo "version: ${{ steps.build.outputs.new_version }}"
          cat .github/release.md
      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ steps.build.outputs.new_version != '' }}
        with:
          body_path: .github/release.md
          files: |
            release/it-quiz-v${{ steps.build.outputs.new_version }}.yaml
            release/it-quiz-v${{ steps.build.outputs.new_version }}.json
            release/news-quiz-v${{ steps.build.outputs.new_version }}.yaml
            release/news-quiz-v${{ steps.build.outputs.new_version }}.json